config/routes.rb
Rails.application.routes.draw do
  resources :reccomendation
  resources :user_reccomendations
  resources :community_reccomendations

  root 'pages#home'
  
  get '/reccomendations', to: 'pages#reccomendations'
  
  post 'search/searchbar', to: 'search#searchbar'
  post 'search/spotify', to: 'search#spotify'
  
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions'
  }

  devise_for :modders, controllers: {
    sessions: 'modders/sessions',
    passwords: 'modders/passwords',
    registrations: 'modders/registrations'
  }

  #Routes per l'OAuth di Google
  get '/redirect', to: 'event_participations#redirect', as: 'redirect'
  get '/callback', to: 'event_participations#callback', as: 'callback'

  post '/events/:id/:calendar_id', to: 'event_participations#create', as: 'new_googlecalendar_event', calendar_id: /[^\/]+/
  delete '/events/:id/:calendar_id', to: 'event_participations#destroy', as: 'delete_googlecalendar_event', calendar_id: /[^\/]+/

  get '/chats/index'
  get '/users/:uid', to: 'users#show', as: 'uid_user'
  get '/users/:uid/edit', to: 'users#edit', as: 'edit_user'
  post '/users/:uid/follow', to: 'users#follow', as: 'follow_user'
  post '/users/:uid/unfollow', to: 'users#unfollow', as: 'unfollow_user'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :posts do
    resources :comments do
      resources :comment_reactions, only: %i[create update destroy]
    end
    resources :reactions, only: %i[create update destroy]
  end

  resources :events do
    resources :users do
      resources :event_participations
    end
  end

  resources :communities do
    resources :posts
    resources :events
  end
  post '/communities/:id/add_playlist', to: 'communities#add_playlist', as: 'community_add_playlist'
  post '/communities/:id/remove_playlist', to: 'communities#remove_playlist',as:'community_remove_playlist'

  resources :users do

    resources :communities do
      resources :participations
    end

    resources :events do
      resources :event_participations
    end
  end

  resources :tags

  resources :chats do
    resources :messages
  end
  post '/chats/:user2_id',
       to: 'chats#create',
       as: 'create_chat'
  post '/users/:user_id/communities/:community_id/participations/create',
       to: 'participations#create',
       as: 'create_user_community_participation'
  post '/users/:user_id/communities/:community_id/participations/ban',
       to: 'participations#ban',
       as: 'ban_user_community_participation'
  post '/users/:user_id/communities/:community_id/participations/unban',
       to: 'participations#unban',
       as: 'unban_user_community_participation'
  post '/users/:user_id/communities/:community_id/participations/promote',
       to: 'participations#promote',
       as: 'promote_user_community_participation'
  post '/users/:user_id/communities/:community_id/participations/demote',
       to: 'participations#demote',
       as: 'demote_user_community_participation'
  post '/users/:user_id/communities/:community_id/participations/move', to: 'participations#move',
                                                                        as: 'move_user_community_participation'
  get '/posts/:post_id/reactions/:id', to: 'reactions#update', as: 'update_post_reaction'
  get '/posts/:post_id/comments/:comment_id/comment_reactions/:id',
      to: 'comment_reactions#update',
      as: 'update_post_comment_comment_reaction'
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
  before_action :authenticate_user!, :set_reaction, only: %i[update destroy]

  def create
    @post = Post.find(params[:post_id])
    @reaction = @post.reactions.new(reaction_params)
    @reaction.user = current_user
    if @reaction.save
      if !@post.community_id.nil?
        @community = Community.find(@post.community_id)
        redirect_back(fallback_location: community_path(@community))
      else
        redirect_back(fallback_location: root_path)
      end
    else
      redirect_to root_path, alert: 'Impossibile inserire la reaction'
    end
  end

  def update
    @reaction = if @reaction.like == true
                  @reaction.update(like: false)
                else
                  @reaction.update(like: true)
                end
    if !@post.community_id.nil?
      @community = Community.find(@post.community_id)
      redirect_back(fallback_location: community_path(@community))
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @reaction.destroy
    if !@post.community_id.nil?
      @community = Community.find(@post.community_id)
      redirect_back(fallback_location: community_path(@community))
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def set_reaction
    @post = Post.find(params[:post_id])
    @reaction = @post.reactions.find(params[:id])
  rescue ActiveRecord::RecordNotFound => e
    redirect_to root_path, notice: e.message
  end

  def reaction_params
    params.require(:reaction).permit(:like)
  end
end

app/helpers/reaction_helper.rb
module ReactionHelper
end

app/views/reactions/_dislike.html.erb
<% if !current_modder && post.reactions.where(user_id: current_user.id).first %> <!-- c è un like/dislike?-->
  <% @reaction = post.reactions.where(user_id: current_user.id).first %>
  <% if @reaction.like == true %>
    <%= button_to raw('<i class="bi bi-hand-thumbs-down"></i>'), update_post_reaction_path(post.id, @reaction.id), class: "btn btn-trasparent col",remote: true,  method: :get%>
  <% else %>
    <%= button_to raw('<i class="bi bi-hand-thumbs-down-fill"></i>'), post_reaction_path(post.id, @reaction.id), class: "btn btn-trasparent col",remote: true, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, method: :delete%>
  <% end %>
<% else %>
  <% unless current_modder %>
    <%= form_with(model: [ post, post.reactions.build ],remote: true) do |form| %>
      <%= form.hidden_field :like, value: false%>
      <button type="submit" class="btn btn-trasparent">
        <i class="bi bi-hand-thumbs-down"></i>
      </button>
    <% end %>
  <% end %>
<% end %>

app/views/reactions/_like.html.erb
<% if !current_modder && post.reactions.where(user_id: current_user.id).first %> <!-- c è un like/dislike?-->
  <% @reaction = post.reactions.where(user_id: current_user.id).first %>
  <% if @reaction.like == true %>
    <%= button_to raw('<i class="bi bi-hand-thumbs-up-fill"></i>'), post_reaction_path(post.id, @reaction.id), class: "btn btn-trasparent col", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, method: :delete%>
  <% else %>
    <%= button_to raw('<i class="bi bi-hand-thumbs-up"></i>'), update_post_reaction_path(post.id, @reaction.id), class: "btn btn-trasparent col", method: :get%>
  <% end %>
<% else %>
  <% unless current_modder %>
    <%= form_with(model: [ post, post.reactions.build ],remote: true) do |form| %>
      <%= form.hidden_field :like, value: true%>
      <button type="submit" class="btn btn-trasparent">
        <i class="bi bi-hand-thumbs-up"></i>
      </button>
    <% end %>
  <% end %>
<% end %>