config/routes.rb
Rails.application.routes.draw do
  resources :reccomendation
  resources :user_reccomendations
  resources :community_reccomendations

  root 'pages#home'
  
  get '/reccomendations', to: 'pages#reccomendations'
  
  post 'search/searchbar', to: 'search#searchbar'
  post 'search/spotify', to: 'search#spotify'
  
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions'
  }

  devise_for :modders, controllers: {
    sessions: 'modders/sessions',
    passwords: 'modders/passwords',
    registrations: 'modders/registrations'
  }

  #Routes per l'OAuth di Google
  get '/redirect', to: 'event_participations#redirect', as: 'redirect'
  get '/callback', to: 'event_participations#callback', as: 'callback'

  post '/events/:id/:calendar_id', to: 'event_participations#create', as: 'new_googlecalendar_event', calendar_id: /[^\/]+/
  delete '/events/:id/:calendar_id', to: 'event_participations#destroy', as: 'delete_googlecalendar_event', calendar_id: /[^\/]+/

  get '/chats/index'
  get '/users/:uid', to: 'users#show', as: 'uid_user'
  get '/users/:uid/edit', to: 'users#edit', as: 'edit_user'
  post '/users/:uid/follow', to: 'users#follow', as: 'follow_user'
  post '/users/:uid/unfollow', to: 'users#unfollow', as: 'unfollow_user'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :posts do
    resources :comments do
      resources :comment_reactions, only: %i[create update destroy]
    end
    resources :reactions, only: %i[create update destroy]
  end

  resources :events do
    resources :users do
      resources :event_participations
    end
  end

  resources :communities do
    resources :posts
    resources :events
  end
  post '/communities/:id/add_playlist', to: 'communities#add_playlist', as: 'community_add_playlist'
  post '/communities/:id/remove_playlist', to: 'communities#remove_playlist',as:'community_remove_playlist'

  resources :users do

    resources :communities do
      resources :participations
    end

    resources :events do
      resources :event_participations
    end
  end

  resources :tags

  resources :chats do
    resources :messages
  end
  post '/chats/:user2_id',
       to: 'chats#create',
       as: 'create_chat'
  post '/users/:user_id/communities/:community_id/participations/create',
       to: 'participations#create',
       as: 'create_user_community_participation'
  post '/users/:user_id/communities/:community_id/participations/ban',
       to: 'participations#ban',
       as: 'ban_user_community_participation'
  post '/users/:user_id/communities/:community_id/participations/unban',
       to: 'participations#unban',
       as: 'unban_user_community_participation'
  post '/users/:user_id/communities/:community_id/participations/promote',
       to: 'participations#promote',
       as: 'promote_user_community_participation'
  post '/users/:user_id/communities/:community_id/participations/demote',
       to: 'participations#demote',
       as: 'demote_user_community_participation'
  post '/users/:user_id/communities/:community_id/participations/move', to: 'participations#move',
                                                                        as: 'move_user_community_participation'
  get '/posts/:post_id/reactions/:id', to: 'reactions#update', as: 'update_post_reaction'
  get '/posts/:post_id/comments/:comment_id/comment_reactions/:id',
      to: 'comment_reactions#update',
      as: 'update_post_comment_comment_reaction'
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :event_participations
    has_many :users, through: :event_participations, dependent: :destroy
    
    belongs_to :user
    belongs_to :community



    validates :title, presence: true
    validates :body, presence: true
    validates :start_date, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_person!, :set_event, only: %i[edit update destroy]

  # GET /events/new
  def new
    @event = Event.new
    @community = Community.find(params[:community_id])
  end

  # GET /events/1/edit
  def edit
    redirect_to root_path, notice: 'Non puoi accedere a questa sezione!' if current_user != @event.user
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to root_path, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { redirect_to new_community_event_path(event_params[:community_id]), status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to root_path, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def new_googlecalendar_event
    client = Signet::OAuth2::Client.new(client_options)
    client.update!(session[:authorization])

    service = Google::Apis::CalendarV3::CalendarService.new
    service.authorization = client

    @event = Event.find(params[:id])

    event_id = @event.id.to_s + 'assi'
    event_date = @event.start_date
    event_title = @event.title

    event = service.get_event('primary', event_id)

    if event
      event.status = 'confirmed'
      event.summary = event_title
      event.start.date = event_date
      event.end.date = event_date + 1

      service.update_event('primary', event_id, event)

    else

      event = {
        id: event_id,
        status: 'confirmed',
        summary: event_title,
        start: {
          date: event_date
        },
        end: {
          date: event_date + 1
        }
      }

      service.insert_event('primary', event)
    end

    nil
  rescue Google::Apis::AuthorizationError
    response = client.refresh!
    session[:authorization] = session[:authorization].merge(response)

    retry
  end

  def delete_googlecalendar_event
    client = Signet::OAuth2::Client.new(client_options)

    redirect_to client.authorization_uri.to_s, allow_other_host: true unless client.code

    client.update!(session[:authorization])

    service = Google::Apis::CalendarV3::CalendarService.new
    service.authorization = client

    @event = Event.find(params[:id])

    event_id = @event.id.to_s + 'assi'

    event_list = service.list_events('primary')

    event_list.items.each do |event|
      if event.id == event_id
        service.delete_event('primary', event.id)
        break
      end
    end

    nil
  rescue Google::Apis::AuthorizationError
    response = client.refresh!

    session[:authorization] = session[:authorization].merge(response)

    retry
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:title, :body, :start_date, :community_id, :user_id)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<li>
  <!-- begin timeline-time -->
  <div class="timeline-time">
    <span class="time"><%=event.created_at.to_fs(:short)%></span>
  </div>
  <!-- end timeline-time -->
  <!-- begin timeline-icon -->
  <div class="timeline-icon">
    <a href="javascript:;">&nbsp;</a>
  </div>
  <!-- end timeline-icon -->
  <!-- begin timeline-body -->
  <div class="timeline-body">
    <div class="row timeline-header">
      <div class="col-10 col-md-11 post-header align-content-center">
        <span class="userimage"><img src="<%=event.user.avatar_url%>" alt="" width="32" height="32" class="rounded-circle"></span>
        <span class="username"><a href="/users/<%= String(event.user.uid) %>"><%= event.user.name %></a></span>
        <%if event.community_id && communities!=nil%>
          <span class="username" style="font-size:80%"> >> <a href="/communities/<%= String(event.community_id) %>"><%= communities.where(id: event.community_id).first().name %></a></span>
        <%end%>
        <small></small>
      </div>
      <% if current_modder || (@user_participation.present? && (@user_participation.role == "admin" || @user_participation.role == "moderator")) %>
        <div class="col-1 justify-content-end" >
          <a class="nav-link" href="#" id="dropdown01" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-three-dots-vertical"></i></a>
          <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdown01">
            <li><%= link_to "Elimina", event_path(event),class: "dropdown-item", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, method: :delete %></li>
          </div>
        <% end %>
      </div>
      <div class="row timeline-content">
        <div class="col">
          <h3><%= event.title %></h3>
          <p><%= event.body %></p>
          <% if !current_modder%>
            <% if current_user.joined_events.include?(event) %>
              <%= button_to "Rimuovi partecipazione", delete_googlecalendar_event_path(event, 'primary'), class:"btn btn-primary", method: :delete %>
            <% else %>
              <%= button_to "Partecipa", new_googlecalendar_event_path(event, 'primary'), class:"btn btn-primary", method: :post %>
            <% end %>
          <% end %>
        </div>
        <div class="col-1 justify-content-end" >
          <a class="nav-link" href="#" id="dropdown01" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-person"></i></a>
          <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdown01">
            <% event.event_participations.each do |participation| %>
              <li>
                <p><%= participation.user.name %></p>
              </li>
            <% end %>
          </div>
        </div>
      </div>
      <!-- end timeline-body -->
    </li>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <p>Inserisci la data di inizio dell'evento</p>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.date_field :start_date %>
  </div>

  <div>
    <%= form.hidden_field :community_id, value: @community.id %>
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Show this event", @event %> |
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Events</h1>

<div id="events">
  <% @events.each do |event| %>
    <%= render event %>
    <p>
      <%= link_to "Show this event", event %>
    </p>
  <% end %>
</div>

<%= link_to "New event", new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render "form", event: @event %>

app/views/events/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @event %>

<div>
  <%= link_to "Edit this event", edit_event_path(@event) %> |
  <%= link_to "Back to events", events_path %>

  <%= button_to "Destroy this event", @event, method: :delete %>
</div>