config/routes.rb
Rails.application.routes.draw do
  resources :reccomendation
  resources :user_reccomendations
  resources :community_reccomendations

  root 'pages#home'
  
  get '/reccomendations', to: 'pages#reccomendations'
  
  post 'search/searchbar', to: 'search#searchbar'
  post 'search/spotify', to: 'search#spotify'
  
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions'
  }

  devise_for :modders, controllers: {
    sessions: 'modders/sessions',
    passwords: 'modders/passwords',
    registrations: 'modders/registrations'
  }

  #Routes per l'OAuth di Google
  get '/redirect', to: 'event_participations#redirect', as: 'redirect'
  get '/callback', to: 'event_participations#callback', as: 'callback'

  post '/events/:id/:calendar_id', to: 'event_participations#create', as: 'new_googlecalendar_event', calendar_id: /[^\/]+/
  delete '/events/:id/:calendar_id', to: 'event_participations#destroy', as: 'delete_googlecalendar_event', calendar_id: /[^\/]+/

  get '/chats/index'
  get '/users/:uid', to: 'users#show', as: 'uid_user'
  get '/users/:uid/edit', to: 'users#edit', as: 'edit_user'
  post '/users/:uid/follow', to: 'users#follow', as: 'follow_user'
  post '/users/:uid/unfollow', to: 'users#unfollow', as: 'unfollow_user'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :posts do
    resources :comments do
      resources :comment_reactions, only: %i[create update destroy]
    end
    resources :reactions, only: %i[create update destroy]
  end

  resources :events do
    resources :users do
      resources :event_participations
    end
  end

  resources :communities do
    resources :posts
    resources :events
  end
  post '/communities/:id/add_playlist', to: 'communities#add_playlist', as: 'community_add_playlist'
  post '/communities/:id/remove_playlist', to: 'communities#remove_playlist',as:'community_remove_playlist'

  resources :users do

    resources :communities do
      resources :participations
    end

    resources :events do
      resources :event_participations
    end
  end

  resources :tags

  resources :chats do
    resources :messages
  end
  post '/chats/:user2_id',
       to: 'chats#create',
       as: 'create_chat'
  post '/users/:user_id/communities/:community_id/participations/create',
       to: 'participations#create',
       as: 'create_user_community_participation'
  post '/users/:user_id/communities/:community_id/participations/ban',
       to: 'participations#ban',
       as: 'ban_user_community_participation'
  post '/users/:user_id/communities/:community_id/participations/unban',
       to: 'participations#unban',
       as: 'unban_user_community_participation'
  post '/users/:user_id/communities/:community_id/participations/promote',
       to: 'participations#promote',
       as: 'promote_user_community_participation'
  post '/users/:user_id/communities/:community_id/participations/demote',
       to: 'participations#demote',
       as: 'demote_user_community_participation'
  post '/users/:user_id/communities/:community_id/participations/move', to: 'participations#move',
                                                                        as: 'move_user_community_participation'
  get '/posts/:post_id/reactions/:id', to: 'reactions#update', as: 'update_post_reaction'
  get '/posts/:post_id/comments/:comment_id/comment_reactions/:id',
      to: 'comment_reactions#update',
      as: 'update_post_comment_comment_reaction'
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user

    has_many :comments, dependent: :destroy
    has_many :reactions, dependent: :destroy

    validates :spotify_content, presence: true
    validates :body, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_person!, :set_post, only: %i[edit update destroy]
  skip_before_action :verify_authenticity_token

  def home
    @posts = Post.all
  end

  def new
    @post = Post.new
    @community = Community.find(params[:community_id]) unless params[:community_id].nil?
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      flash[:notice] = 'Post creato con successo.'
      redirect_to root_path
    else
      flash[:alert] = 'Il post non è stato creato. Riprova.'
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    redirect_to root_path, notice: 'Non puoi accedere a questa sezione!' if current_user != @post.user
  end

  def update
    if @post.update(post_params)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if current_user == @post.user || current_modder || (!@post.community_id.nil? && (current_user.participations.where(community_id: @post.community_id).first.role=="admin"||current_user.participations.where(community_id: @post.community_id).first.role=="moderator"))
      @post.destroy
      redirect_to root_path, status: :see_other
    else
      redirect_to root_path, notice: 'Non puoi accedere a questa sezione!'
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  rescue ActiveRecord::RecordNotFound => e
    redirect_to root_path, notice: e.message
  end

  def post_params
    params.require(:post).permit(:spotify_content, :body, :community_id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div>
<%= form_with(url: search_spotify_path, method: :post, class:"ms-2 col-6") do |form| %>
    <%= form.search_field :name_search, placeholder: "Cerca canzoni artisti album o playlists", class: "form-control",oninput:"this.form.requestSubmit()" %>
<% end %>
<div id="spotify_results" class="row"></div>
</div>
<script>
    function select(btn_id) {
        var sc = document.getElementById("post_spotify_content");
        var si = document.getElementById("spotify_iframe");
        var input = document.getElementById("name_search");
        var results = document.getElementById("spotify_results");
        sc.value=btn_id;
        si.innerHTML='<iframe style="border-radius:12px" src="https://open.spotify.com/embed?uri='+btn_id+'" width="50%" height="80" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe>';
        input.value="";
        results.innerHTML="";

        
    }
</script>
<div id="spotify_iframe">
            </div>
<% if community == nil %>
    <%= form_with model: @post do |form| %>
        <div>
            Hai selezionato:
            <%= form.hidden_field :spotify_content %>
            <div id="spotify_iframe">
            </div>
        </div>

        <div>
            <%= form.label :body %>
            <%= form.text_area :body %>
        </div>

        <div>
            <%= form.submit %>
        </div>
    <% end %>
<% else %>
    <%= form_with model: [community, community.posts.build] do |form| %>
        <div>
            Hai selezionato:
            <%= form.hidden_field :spotify_content %>
            <div id="spotify_iframe">
            </div>
        </div>

        <div>
            <%= form.label :body %>
            <%= form.text_area :body %>
        </div>

        <% if post.community_id == nil %>
            <%= form.hidden_field :community_id, value: community.id%>
        <% end %>

        <div>
            <%= form.submit %>
        </div>

    <% end %>
<% end %>

app/views/posts/_post.html.erb
<% if current_modder || post.user == current_user || (current_user.followings.include?(post.user) && !post.community_id) || (post.community_id && current_user.communities.where(id: post.community_id).first)%>
  <li>
    <!-- begin timeline-time -->
    <div class="timeline-time">
      <span class="time"><%=post.created_at.to_fs(:short)%></span>
    </div>
    <!-- end timeline-time -->
    <!-- begin timeline-icon -->
    <div class="timeline-icon">
      <a href="javascript:;">&nbsp;</a>
    </div>
    <!-- end timeline-icon -->
    <!-- begin timeline-body -->
    <div class="timeline-body">
      <% puts post.id %>
      <div class="row timeline-header">
        <div class="col-10 col-md-11 post-header align-content-center">
          <%if post.user.avatar_url%>
            <span class="userimage"><img src="<%=post.user.avatar_url%>" alt="" width="32" height="32" class="rounded-circle"></span>
          <%else%>
            <span class="userimage"><%= image_tag "prof_pic_default.png" , class: "rounded-circle"%></span>
          <%end%>
          <span class="username"><a href="/users/<%= String(post.user.uid) %>"><%= post.user.name %></a></span>
          <%if !post.community_id.nil? && communities!=nil%>
            <span class="username" style="font-size:80%"> >> <a href="/communities/<%= String(post.community_id) %>"><%= communities.where(id: post.community_id).first().name %></a></span>
          <%end%>
          <small></small>
        </div>
        <div class="col-1 justify-content-end" >
          <% if current_modder  ||(!post.community_id.nil? && current_user.participations.where(community_id: post.community_id).first&&(current_user.participations.where(community_id: post.community_id).first.role=="admin"||current_user.participations.where(community_id: post.community_id).first.role=="moderator"))%>
            <a class="nav-link" href="#" id="dropdown01" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-three-dots-vertical"></i></a>
            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdown01">
              <li><%= link_to "Elimina", post_path(post),class: "dropdown-item", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, method: :delete %></li>
            </div>
          <% elsif post.user == current_user%>
            <a class="nav-link" href="#" id="dropdown01" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-three-dots-vertical"></i></a>
            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdown01">
              <li><%= link_to "Modifica", edit_post_path(post),class: "dropdown-item", method: :get %></li>
              <li><%= link_to "Elimina", post_path(post),class: "dropdown-item", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, method: :delete %></li>
            </div>
          <% else %>
            <div style="padding: 17pt"> </div>
          </div>
        <% end %>
      </div>
      <div class="timeline-content">
        <iframe style="border-radius:12px" src="https://open.spotify.com/embed?uri=<%= post.spotify_content %>" width="100%" height="80" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe>
        <p><%= post.body %></p>
      </div>
      <div class="timeline-likes">
        <div class="stats-right">
          <span class="stats-text" onclick="HideShow<%=post.id %>()"><%= post.comments.count %> Commenti</span>
        </div>
        <div class="row stats">
          <div class="stats-icon"style="float: left; width: auto;">
            <%= render "reactions/like", post: post %>
          </div>
          <div class="col-1 stats-total" style="padding-left: 0px; margin-top: 4px">
            <h5><%= post.reactions.where(like: true).count %></h5>
          </div>
          <div class="stats-icon" style="float: left; width: auto;">
            <%= render "reactions/dislike", post: post %>
          </div>
          <div class="col-1 stats-total" style="padding-left: 0px; margin-top: 4px">
            <h5><%= post.reactions.where(like: false).count %></h5>
          </div>
        </div>
      </div>
      <div class="timeline-comment-box row" id="comment_post_<%=post.id %>" style=  "display: none" >
        <ul class="list-group">
          <% post.comments.each do |comment| %>
            <%= render "comments/comment", post: post, comment: comment, communities: communities%>
          <% end %>
        </ul>
        <%unless current_modder%>
          <div class="col-12 form-group input " style= "padding-left: 0px">
            <%= form_with model: [ post, post.comments.build ] do |form| %>
              <div class="input-group" style="padding-top: 10px">
                <%= form.text_field :body,class:"form-control comment-content" %>
                <%= form.submit "Invia",class: 'btn btn-primary', style:"font: 10px" %>
              </div>
            <% end %>
          </div>
        <%end%>
      </div>
    </div>
    <!-- end timeline-body -->
  </li>
<% end %>
<script>
  function HideShow<%=post.id %>() {
    var x = document.getElementById("comment_post_<%=post.id %>");
    if (x.style.display === "none") {
      x.style.display = "block";
    } else {
      x.style.display = "none";
    }
  }
</script>

app/views/posts/edit.html.erb
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
        <meta name="generator" content="Hugo 0.88.1">
        <title>Offcanvas navbar template · Bootstrap v5.1</title>
        <!-- Bootstrap core CSS -->
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <!-- Custom styles for this template -->

    </head>
    <body class="bg-light">
        <%= render "partials/navbar" %>
        <div style="padding: 40pt"></div>
        <h1> Modifica post </h1>
        <%= render "form", community: @community, post: @post %>
    </body>
</html>

app/views/posts/new.html.erb
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
        <meta name="generator" content="Hugo 0.88.1">
        <title>Offcanvas navbar template · Bootstrap v5.1</title>
        <!-- Bootstrap core CSS -->
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <!-- Custom styles for this template -->

    </head>
    <body class="bg-light">
        <%= render "partials/navbar" %>
        <div style="padding: 40pt"></div>
        <h1> Crea un nuovo post </h1>
            <%= render "form", community: @community, post: @post %>
    </body>
</html>